### ISSUE TITLE
How to get "libxmrig-cuda.so"

### ISSUE THREAD

**Issue by BIGBEASTISHANK** [xmrig/xmrig-cuda#141]
how to get that file, I am on linux and I want to mine with gpu but i cant get that cuda file libxmrig-cuda.so. how to get it?

**Comment by Wolfcoool** [comment]
Compile the program from source 
(guide: https://xmrig.com/docs/miner/build)
select your distro and look under "cuda"

**Comment by Spudz76** [comment]
Download correct CUDA Toolkit for your GPU (if it's Kepler or older use 10.2 if it's Fermi you must use 8.0, otherwise the latest works).  This toolkit should also match the CUDA version in your chosen driver, Fermi can't go above 390 series, Kepler not above 470 series.  To see the CUDA included with your driver use `nvidia-smi` and it's in the upper right corner.
