### ISSUE TITLE
CUDA, RTX 3060, CryptonightR not compatible.

### ISSUE THREAD

**Issue by waynoedm** [xmrig/xmrig-cuda#142]
Can't seem to get this algorythm to work with CUDA. Tried several versions of XMRIG and the CUDA plugin. Getting the following error.

thread #0 failed with error <CryptonightR_build_program>:204 "NVRTC_ERROR_INVALID_OPTION"

**Comment by Spudz76** [comment]
Default build does not (yet) support arch 86 you have to build your own using at least CUDA Toolkit 11.1.1  (11.1.0 the first version to know about the arch 86 cards, had bugs)

Also ensure your driver contains the minimal version of the CUDA runtime to match the Toolkit.  `nvidia-smi` shows in the upper right corner.  If you're Windows the nvidia-smi.exe is hidden down in some NVIDIA folder somewhere I forget.

**Comment by waynoedm** [comment]
Thanks. That did the trick.

**Comment by Spudz76** [comment]
I am composing some CMake changes which just poll the list of supported architectures directly from the `nvcc --help` output so it just follows exactly what each Toolkit supports (even brand new 90 series RTX4xxx it should just follow along when nvcc has new support...).

Currently the logic is a bit complicated and needs to be taught manually about new stuff, and it hasn't been re-updated since '86' came out.  And would break again when '90' comes out... this should just work instantly.

**Comment by waynoedm** [comment]
Slick. Sounds like the way to go. :D Thanks.
