### ISSUE TITLE
xmrig-5.0.1 combined cpu+nv lower hash rate than separate cpu,nv

### ISSUE THREAD

**Issue by kl1059** [xmrig/xmrig-cuda#18]
(with xmrig-cuda-2.0.1-beta)

running combined xmrig-5.0.1 cpu + nvidia-gpu results in 18% lower reported
hash rate than running separate xmrig-5.0.1 cpu and nvidia-gpu processes.

separate xmrig-5.0.1 cpu and nvidia-gpu processes are able to achieve the 
same hash rate as xmrig-3.2.1 cpu + xmrig-nvidia-2.14.5 gpu processes.

running combined with one less cpu thread increases hash rate 14% but the
overall hash rate is still 4% lower than running separate processes.

i'm going to guess that something in the cuda code isn't asynchronous enough
and is blocking one or two cpu threads from hashing at full speed.

(or could bsleep/bfactor be incorrectly applied to the cpu threads?)

**Comment by Spudz76** [comment]
Multi backend is still chained to single jobs.  So if your CPU finishes early (gets luck) then it has to wait and do nothing until the GPU finishes its subdivision of the job, so that a new 2-backend job can be split up and assigned.  Jobs are divided by hashrate but there will always be loss from waiting to sync.

Solution is as you've found, run two xmrigs one with CPU only and the other with CPU disabled.  This also allows them to run different algos (RandomX sucks on GPUs, by design).
