### ISSUE TITLE
Hash Rate - CPU hash is cut by what CUDA plugin is Adding

### ISSUE THREAD

**Issue by cdndcminer** [xmrig/xmrig-cuda#25]
xmrig 5.1.1 cuda plugin 2.1.1. 

If i run xmrig i get 1500h/s, when i add the GPU by the cuda plugin(2.1.1) my CPU hash rate drops by what the NV(GPU) hash rate is able to produce.

Example if GPU produces 200h/s my CPU drops to 1300h/s.

bug?

**Comment by Spudz76** [comment]
Run separate miners, one with CPU only, one with CPU disabled but GPUs enabled.
Set affinity on GPU one so that it is never on cores the CPU mining is using (may be impossible unless you have over-cored and under-cached type of CPU).

The hash loss is more likely from wait states, to keep the two totally different backends in sync working on one single job.  The CPU is not given more work until all backends complete the last work so you can only be as lucky as your least lucky device.  There are none such waits if you run two xmrigs one on each "class" of device.  Also RandomX sucks on GPU anyway so running separate lets you choose the best HashPerWatt of each device (and use MoneroOcean to payout whatever coins to XMR automatically).
