### ISSUE TITLE
2.0.1 detected as malware on Windows

### ISSUE THREAD

**Issue by michael-pesce** [xmrig/xmrig-cuda#26]
Win32/Contebrew.A!ml appears to be baked into the compiled windows 10_1 download. 

Beware and avoid.

**Comment by Spudz76** [comment]
Windows Defender added a bunch of miner apps due to trojan installations, false positive.
It would also complain if you compiled it yourself, try it and see!

Proper workaround is to beware and avoid virus scanners if you work in a hacker-adjacent hobby they will false positive all the time.  I have entire sections of my drives marked whitelisted so it leaves me alone about various network scanners or brute force audit tools or miners or... things that don't belong on a computer unless you are the one putting them there (the whole reason for whitelisting).
