### ISSUE TITLE
how the fuck can I compile this mf plugin in linux

### ISSUE THREAD

**Issue by brutephishing** [xmrig/xmrig-cuda#34]
I tried with every fucking way in cmake and is giving me a bunch of errors and a fucking headache

why the fuck the developer of this shit (that is getting fees in the miner) doesnt compile this piece of bullshit?

**Comment by Spudz76** [comment]
Thousands of us compile it with zero issues.  Plus we can't help you if you've not bothered to post any of these errors.  Also we have no idea which Linux distro, you might be shooting yourself in the foot by using anything but Ubuntu.

Also most of your anger probably belongs with nVidia since the whole getting CUDA working thing is kind of a clunkfest, even on Ubuntu.

One big clunk is when you install CUDA it doesn't always make a link from `/usr/local/cuda/` to the versioned directory (like `/usr/local/cuda-10.2/') and then it is not found automatically.  So go to `/usr/local/` and remove any broken `cuda` link and symbolic link it to `cuda-10.2` or whatever version you're using (`ln -s /usr/local/cuda-10.2 /usr/local/cuda`).

The other big one is if your GPU is old like Fermi architecture 2x then you have to use CUDA8 because nVidia dropped all support for those in everything newer and it will never be restored.  A chained gotcha there is it won't compile without GCC5 (newer than that will never work).  So then you compile this plugin with GCC5 but then can compile the app side xmrig with whatever you like (I use Clang-11) and they can play together.  This was one of the major reasons to split it into a plugin, only the part that talks to CUDA needs to be compiled with an nVidia-approved compiler version.

Even CUDA 10.2 won't let you use GCC9 it caps out at GCC8.

You may need to add toolchain PPA (ubuntu-toolchain-r-test) to get odd versions of GCC that aren't mainstream.

**Comment by theraw** [comment]
@Spudz76 don't know why you bother write that much when owner @xmrig itself doesn't even give a puck bout it can't even write a proper wiki on how to compile his projects, the guy either won't give support for his code or wants to pay him to compile it for you.
I've been using xmrig for some time his proxy, gpu/cpu miners and i can for sure tell when time comes to compile or do something is pure bullshit and the guy closes issues like 0 fucks given.

this is how a normal mining software should push 
![image](https://user-images.githubusercontent.com/32969774/95379833-30410580-08e6-11eb-9cc8-a4e5663fbc36.png)


This is what happens when you use xmrig + proxy
![image](https://user-images.githubusercontent.com/32969774/95379907-48188980-08e6-11eb-8edd-8b70567f9cef.png)
spaghetti-rig i have some idea why but i won't even ask because i doubt i'll get any response. Just moving away as soon as i can find a better software.
