### ISSUE TITLE
failed to load libxmrig_cuda.so on Linux

### ISSUE THREAD

**Issue by magnus-i** [xmrig/xmrig-cuda#9]
Build xmrig b4.5 and xmrig-cuda b2.0 on ubuntu 19.10 with gcc7 fine.
Problem is xmrig doesnt find the libxmrig-cuda.so . Tried "libxmrig-cuda.so "./..." and also the absolute path. Also tried command line and config file.

` * CUDA         disabled (failed to load CUDA plugin)
`

`    "cuda": { `
`        "enabled": true,`
`        "loader": "libxmrig-cuda.so",`
`        "nvml": true`
`    },`

**Comment by kl1059** [comment]
on Fedora i was able to use the command line this way:
   --cuda-loader=/home/miner/monero/libxmrig-cuda.so
initially i was using /home/miner/monero (path is kind of an ambiguous term) and got the same fail
you should also do an ldd on the libxmrig-cuda.so and make sure it can see where the cuda libraries
are - if not you may have to use LD_LIBRARY_PATH to point at them

**Comment by Emperornero** [comment]
Checking in.

Also unable to use cuda loader on Ubuntu 19.10 with Cuda 10.2.  ldd libxmrig-cuda.so returns as being able to see all Cuda LD libraries, however, the loader doesn't work with both the config "cuda-loader": "./libxmrig-cuda.so" option, or by running --cuda-loader=./libxmrig-cuda.so.

Not sure what the problem is.

**Comment by pkudel4** [comment]
checking in as well, Im running centos 8 workstation, cuda 10.2, ldd shows libraries, tried multiple paths too - failed to load CUDA plugin
